name: CD Docker Build & Push

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build und Push Docker-Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build und Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mygameslist:latest,${{ secrets.DOCKERHUB_USERNAME }}/mygameslist:${{ github.sha }}

  deploy:
    name: Deploy Application
    needs: build
    runs-on: self-hosted
    steps:
      - name: Restart application
        run: |
          docker stop my-games-list || true
          docker rm my-games-list || true
          docker run -d --name my-games-list --network ${{ secrets.DOCKER_NETWORK_NAME }} -e MONGODB_URI=${{ secrets.MONGODB_URI }} ${{ secrets.DOCKERHUB_USERNAME }}/mygameslist:${{ github.sha }}